- name: Configure Consul
  hosts: localhost
  connection: local
  gather_facts: true
  tasks:
    - name: Set Parameters
      set_fact:
        datacenter: 'dc1'
        cluster_ips:
          - '10.0.3.101'
          - '10.0.3.102'
          - '10.0.3.103'
        encryption_key: 'AyXuIOdn351tptMQN1nZHMlIdMgBm32P3Ha7dbuOk3I='

    - name: Create retry_join value
      set_fact:
        retry_join: "\"{{ cluster_ips | join('\",\"') }}\""

    - name: Write Consul config file
      copy:
        dest: /etc/consul.d/consul.hcl
        content: |
          datacenter = "{{ datacenter }}"
          data_dir = "/opt/consul"
          bootstrap_expect = 3
          bind_addr = "0.0.0.0"
          client_addr = "127.0.0.1 {{ '{{' }} GetInterfaceIP  \"{{ ansible_default_ipv4.interface }}\" {{ '}}' }} {{ '{{' }} GetInterfaceIP  \"docker0\" {{ '}}' }}"
          advertise_addr = "{{ '{{' }} GetInterfaceIP \"{{ ansible_default_ipv4.interface }}\" {{ '}}' }}"
          encrypt = "{{ encryption_key }}"
          retry_join = [{{ retry_join }}]
          server = true
          ui_config {
            enabled = true
          }
        mode: '0644'

    - name: Restart Consul to apply new config
      shell: systemctl restart consul
      args:
        warn: false
